/*
 * Deborah Kronk-Lewis
 * IT252: Intermediate Java Programming II
 * Unit 1 IP
 */
package IT252_Unit1;

//import statements
import javax.swing.JOptionPane;


public class MainApp extends javax.swing.JFrame {

    //initialize form and error messages
    public MainApp() {
        initComponents();
        idError.setVisible(false);
        firstNameError.setVisible(false);
        lastNameError.setVisible(false);
        suppliesError.setVisible(false);
        booksError.setVisible(false);
        paperError.setVisible(false);
        districtError.setVisible(false); 
        contactError.setVisible(false); 
    }
    
    //initialize salesRep object
    SalesRep s = new SalesRep();
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupContact = new javax.swing.ButtonGroup();
        btnGroupDistrict = new javax.swing.ButtonGroup();
        panelTitle = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        panelSalesRep = new javax.swing.JPanel();
        labelSalesRep = new javax.swing.JLabel();
        labelRepId = new javax.swing.JLabel();
        idInput = new javax.swing.JTextField();
        idError = new javax.swing.JLabel();
        labelFirstName = new javax.swing.JLabel();
        firstNameInput = new javax.swing.JTextField();
        labelLastName = new javax.swing.JLabel();
        lastNameInput = new javax.swing.JTextField();
        lastNameError = new javax.swing.JLabel();
        firstNameError = new javax.swing.JLabel();
        panelSales = new javax.swing.JPanel();
        labelSales = new javax.swing.JLabel();
        labelSupplies = new javax.swing.JLabel();
        suppliesInput = new javax.swing.JTextField();
        suppliesError = new javax.swing.JLabel();
        labelBooks = new javax.swing.JLabel();
        booksInput = new javax.swing.JTextField();
        booksError = new javax.swing.JLabel();
        labelPaper = new javax.swing.JLabel();
        paperInput = new javax.swing.JTextField();
        paperError = new javax.swing.JLabel();
        panelDistrict = new javax.swing.JPanel();
        labelDistrict = new javax.swing.JLabel();
        northButton = new javax.swing.JRadioButton();
        southButton = new javax.swing.JRadioButton();
        eastButton = new javax.swing.JRadioButton();
        westButton = new javax.swing.JRadioButton();
        districtError = new javax.swing.JLabel();
        panelContact = new javax.swing.JPanel();
        labelContact = new javax.swing.JLabel();
        phoneButton = new javax.swing.JRadioButton();
        emailButton = new javax.swing.JRadioButton();
        visitButton = new javax.swing.JRadioButton();
        contactError = new javax.swing.JLabel();
        panelFormNav = new javax.swing.JPanel();
        quitButton = new javax.swing.JButton();
        enterButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("SalesEntryForm"); // NOI18N

        labelTitle.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        labelTitle.setLabelFor(this);
        labelTitle.setText("College Supplies Sales Entry Form");

        javax.swing.GroupLayout panelTitleLayout = new javax.swing.GroupLayout(panelTitle);
        panelTitle.setLayout(panelTitleLayout);
        panelTitleLayout.setHorizontalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelTitleLayout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(labelTitle)
                    .addContainerGap(24, Short.MAX_VALUE)))
        );
        panelTitleLayout.setVerticalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelTitleLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(labelTitle)
                    .addContainerGap(20, Short.MAX_VALUE)))
        );

        panelSalesRep.setPreferredSize(new java.awt.Dimension(700, 100));

        labelSalesRep.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        labelSalesRep.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelSalesRep.setLabelFor(panelSalesRep);
        labelSalesRep.setText("Sales Representative");
        labelSalesRep.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        labelRepId.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        labelRepId.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelRepId.setLabelFor(idInput);
        labelRepId.setText("ID: ");

        idInput.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        idInput.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        idInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idInputActionPerformed(evt);
            }
        });

        idError.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        idError.setForeground(new java.awt.Color(255, 0, 0));
        idError.setLabelFor(idInput);
        idError.setText("* Integer value required");

        labelFirstName.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        labelFirstName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFirstName.setLabelFor(firstNameInput);
        labelFirstName.setText("First Name: ");

        firstNameInput.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        firstNameInput.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        firstNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameInputActionPerformed(evt);
            }
        });

        labelLastName.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        labelLastName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelLastName.setLabelFor(lastNameInput);
        labelLastName.setText("Last Name: ");

        lastNameInput.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lastNameInput.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        lastNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameInputActionPerformed(evt);
            }
        });

        lastNameError.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lastNameError.setForeground(new java.awt.Color(255, 0, 0));
        lastNameError.setLabelFor(lastNameInput);
        lastNameError.setText("* Required");

        firstNameError.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        firstNameError.setForeground(new java.awt.Color(255, 0, 0));
        firstNameError.setLabelFor(firstNameInput);
        firstNameError.setText("* Required");

        javax.swing.GroupLayout panelSalesRepLayout = new javax.swing.GroupLayout(panelSalesRep);
        panelSalesRep.setLayout(panelSalesRepLayout);
        panelSalesRepLayout.setHorizontalGroup(
            panelSalesRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSalesRepLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelSalesRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSalesRepLayout.createSequentialGroup()
                        .addComponent(labelRepId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelSalesRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelSalesRepLayout.createSequentialGroup()
                                .addComponent(idInput, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelFirstName))
                            .addGroup(panelSalesRepLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(idError)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelSalesRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelSalesRepLayout.createSequentialGroup()
                                .addComponent(firstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelLastName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(panelSalesRepLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(firstNameError)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(panelSalesRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelSalesRepLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lastNameError))))
                    .addGroup(panelSalesRepLayout.createSequentialGroup()
                        .addComponent(labelSalesRep)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelSalesRepLayout.setVerticalGroup(
            panelSalesRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSalesRepLayout.createSequentialGroup()
                .addComponent(labelSalesRep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelSalesRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRepId)
                    .addComponent(labelFirstName)
                    .addComponent(firstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSalesRepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idError)
                    .addComponent(lastNameError)
                    .addComponent(firstNameError))
                .addGap(83, 83, 83))
        );

        panelSales.setPreferredSize(new java.awt.Dimension(700, 100));

        labelSales.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        labelSales.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelSales.setLabelFor(panelSales);
        labelSales.setText("Sales ");
        labelSales.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        labelSupplies.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        labelSupplies.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelSupplies.setLabelFor(suppliesInput);
        labelSupplies.setText("Supplies: ");

        suppliesInput.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        suppliesInput.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        suppliesInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppliesInputActionPerformed(evt);
            }
        });

        suppliesError.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        suppliesError.setForeground(new java.awt.Color(255, 0, 0));
        suppliesError.setLabelFor(suppliesInput);
        suppliesError.setText("* Double value required");

        labelBooks.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        labelBooks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBooks.setLabelFor(booksInput);
        labelBooks.setText("Books: ");

        booksInput.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        booksInput.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        booksInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booksInputActionPerformed(evt);
            }
        });

        booksError.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        booksError.setForeground(new java.awt.Color(255, 0, 0));
        booksError.setLabelFor(booksInput);
        booksError.setText("* Double value required");

        labelPaper.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        labelPaper.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelPaper.setLabelFor(paperInput);
        labelPaper.setText("Paper: ");

        paperInput.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        paperInput.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        paperInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paperInputActionPerformed(evt);
            }
        });

        paperError.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        paperError.setForeground(new java.awt.Color(255, 0, 0));
        paperError.setLabelFor(paperInput);
        paperError.setText("* Double value required");

        javax.swing.GroupLayout panelSalesLayout = new javax.swing.GroupLayout(panelSales);
        panelSales.setLayout(panelSalesLayout);
        panelSalesLayout.setHorizontalGroup(
            panelSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSalesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelSalesLayout.createSequentialGroup()
                        .addComponent(labelSales)
                        .addGap(171, 171, 171))
                    .addGroup(panelSalesLayout.createSequentialGroup()
                        .addComponent(labelSupplies)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelSalesLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(suppliesError))
                            .addComponent(suppliesInput, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(labelBooks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSalesLayout.createSequentialGroup()
                        .addComponent(booksInput, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelPaper))
                    .addGroup(panelSalesLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(booksError)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paperInput, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelSalesLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(paperError)))
                .addContainerGap())
        );
        panelSalesLayout.setVerticalGroup(
            panelSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSalesLayout.createSequentialGroup()
                .addComponent(labelSales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suppliesInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSupplies)
                    .addComponent(labelBooks)
                    .addComponent(booksInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paperInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPaper))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(booksError)
                    .addComponent(paperError)
                    .addComponent(suppliesError))
                .addGap(32, 32, 32))
        );

        panelDistrict.setPreferredSize(new java.awt.Dimension(700, 100));

        labelDistrict.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        labelDistrict.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelDistrict.setLabelFor(panelDistrict);
        labelDistrict.setText("Sales District");
        labelDistrict.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnGroupDistrict.add(northButton);
        northButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        northButton.setText("North");
        northButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                northButtonActionPerformed(evt);
            }
        });

        btnGroupDistrict.add(southButton);
        southButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        southButton.setText("South");

        btnGroupDistrict.add(eastButton);
        eastButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        eastButton.setText("East");

        btnGroupDistrict.add(westButton);
        westButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        westButton.setText("West");

        districtError.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        districtError.setForeground(new java.awt.Color(255, 0, 0));
        districtError.setLabelFor(labelDistrict);
        districtError.setText("* Required");

        javax.swing.GroupLayout panelDistrictLayout = new javax.swing.GroupLayout(panelDistrict);
        panelDistrict.setLayout(panelDistrictLayout);
        panelDistrictLayout.setHorizontalGroup(
            panelDistrictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDistrictLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelDistrictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(districtError)
                    .addComponent(labelDistrict)
                    .addGroup(panelDistrictLayout.createSequentialGroup()
                        .addComponent(northButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(southButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eastButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(westButton)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        panelDistrictLayout.setVerticalGroup(
            panelDistrictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDistrictLayout.createSequentialGroup()
                .addComponent(labelDistrict)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDistrictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(northButton)
                    .addComponent(southButton)
                    .addComponent(eastButton)
                    .addComponent(westButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(districtError)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        panelContact.setPreferredSize(new java.awt.Dimension(700, 100));

        labelContact.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        labelContact.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelContact.setLabelFor(panelContact);
        labelContact.setText("Preferred Contact Method");
        labelContact.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnGroupContact.add(phoneButton);
        phoneButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        phoneButton.setText("Phone");

        btnGroupContact.add(emailButton);
        emailButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        emailButton.setText("Email");

        btnGroupContact.add(visitButton);
        visitButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        visitButton.setText("Visit");

        contactError.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        contactError.setForeground(new java.awt.Color(255, 0, 0));
        contactError.setLabelFor(labelContact);
        contactError.setText("* Required");

        javax.swing.GroupLayout panelContactLayout = new javax.swing.GroupLayout(panelContact);
        panelContact.setLayout(panelContactLayout);
        panelContactLayout.setHorizontalGroup(
            panelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContactLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contactError)
                    .addGroup(panelContactLayout.createSequentialGroup()
                        .addComponent(phoneButton)
                        .addGap(18, 18, 18)
                        .addComponent(emailButton)
                        .addGap(18, 18, 18)
                        .addComponent(visitButton))
                    .addComponent(labelContact))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        panelContactLayout.setVerticalGroup(
            panelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContactLayout.createSequentialGroup()
                .addComponent(labelContact)
                .addGap(4, 4, 4)
                .addGroup(panelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneButton)
                    .addComponent(emailButton)
                    .addComponent(visitButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(contactError)
                .addContainerGap())
        );

        quitButton.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        enterButton.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        enterButton.setText("Enter");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFormNavLayout = new javax.swing.GroupLayout(panelFormNav);
        panelFormNav.setLayout(panelFormNavLayout);
        panelFormNavLayout.setHorizontalGroup(
            panelFormNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormNavLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(enterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        panelFormNavLayout.setVerticalGroup(
            panelFormNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormNavLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quitButton)
                    .addComponent(enterButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelSalesRep, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
                            .addComponent(panelSales, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(panelDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelContact, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 19, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(panelFormNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSalesRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelSales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFormNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idInputActionPerformed

    private void firstNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameInputActionPerformed

    private void lastNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameInputActionPerformed

    private void suppliesInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppliesInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suppliesInputActionPerformed

    private void booksInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booksInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_booksInputActionPerformed

    private void paperInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paperInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paperInputActionPerformed

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
       
        /*
         * WHEN THE ENTER BUTTON IS PRESSED
         * 1. Validate data
         * 2. If all data is received & is valid display confirmation message
         */ 
        
        //Set Data Validator to true
        boolean allDataReceived = true; //initialize data validator as true
        
        //Accept repId entry      
        String repIdString = idInput.getText(); 
        
        //Make sure that entry exists
        try {
            if (repIdString.trim().length() == 0) { //if field with whitespace removed is empty
                idError.setVisible(true); //display error message
                idError.setText("* Required"); //let user know that field is required
                allDataReceived = false; //if all data is not received do not show confirm message
            } else {
            //Populate valid entry into SalesRep object    
            int repId = Integer.parseInt(repIdString.trim()); //convert rep id to an integer and trim whitespace
            s.setRepId(repId); //add integer value to SalesRep object
            idError.setVisible(false); //hide error message
            }
            //Make sure that entry is an integer
        } catch (Exception e) { //if it's not an integer
            idError.setVisible(true); //display error message
            idError.setText("* Id must be an integer"); //let user know that field must be an int
            allDataReceived = false; //if all data is not received do not show confirm message
        } 
        
        //Accept firstName entry
        String firstName = firstNameInput.getText(); //accept first name entry
        
        //Make sure that entry exists
        if (firstName.trim().length() == 0) { //if field with whitespace removed is empty
            firstNameError.setVisible(true); //display error message
            firstNameError.setText("* Required"); //let user know that field is required
            allDataReceived = false; //if all data is not received do not show confirm message
        } else {
            //Populate valid entry into SalesRep object
            s.setFirstName(firstName.trim()); //add trimmed firstName string to salesRep object
            firstNameError.setVisible(false); //hide error message
        }
        
        //Accept lastName entry
        String lastName = lastNameInput.getText(); //accept last name entry
        
        //Make sure that entry exists
        if (lastName.trim().length() == 0) { //if field with whitespace removed is empty
            lastNameError.setVisible(true); //display error message
            lastNameError.setText("* Required"); //let user know that field is required
            allDataReceived = false; //if all data is not received do not show confirm message
        } else {
            //Populate valid entry into SalesRep object
            s.setLastName(lastName.trim()); //add trimmed lastName string to salesRep object
            lastNameError.setVisible(false); //hide error message
        }
        
        //Accept supplies entry
        String suppliesString = suppliesInput.getText(); //accept supplies String entry
        
        //Make sure that entry exists
        try {
            if (suppliesString.trim().length() == 0) { //if field with whitespace removed is empty
                suppliesError.setVisible(true); //display error message
                suppliesError.setText("* Required (enter 0 for no sales"); //let user know that field is required
                allDataReceived = false; //if all data is not received do not show confirm message
        } else {
            //Populate valid entry into SalesRep object    
            double supplies = Double.parseDouble(suppliesString); //convert supplies to a double
            s.setSupplies(supplies); //add supplies entry to salesRep object
            suppliesError.setVisible(false); //hide error message
            }
            //Make sure that entry is a double
        } catch (Exception e) { //if it's not a double
            suppliesError.setVisible(true); //display error message
            suppliesError.setText("* Must be a double"); //let user know that value must be a double
            allDataReceived = false; //if all data is not received do not show confirm message
        }
        
        //Accept books entry
        String booksString = booksInput.getText(); //accept books String entry
        
        //Make sure that entry exists
        try {
            if (booksString.trim().length() == 0) { //if field with whitespace removed is empty
                booksError.setVisible(true); //display error message
                booksError.setText("* Required (enter 0 for no sales"); //let user know that field is required
                allDataReceived = false; //if all data is not received do not show confirm message
        } else {
            //Populate valid entry into SalesRep object
            double books = Double.parseDouble(booksString); //convert books to a double
            s.setBooks(books); // add books entry to salesRep object
            booksError.setVisible(false); //hide error message
            }
            //Make sure that entry is a double
        } catch (Exception e) { //if its not a double
            booksError.setVisible(true); //display error message
            booksError.setText("* Must be a double"); //let user know that value must be a double
            allDataReceived = false; //if all data is not received do not show confirm message
        }

        //Accept apaper entry
        String paperString = paperInput.getText(); //accept paperString String entry
        
        //Make sure that entry exists
        try {
            if (paperString.trim().length() == 0) { //if field with whitespace removed is empty
                paperError.setVisible(true); //display error message
                paperError.setText("* Required (enter 0 for no sales"); //let user know that field is required
                allDataReceived = false; //if all data is not received do not show confirm message
        } else {
            //Populate valid entry into SalesRep object
            double paper = Double.parseDouble(paperString); //convert paper to a double
            s.setPaper(paper); // add paper entry to salesRep object
            paperError.setVisible(false); //hide error message
            }
          //Make sure that entry is a double
        } catch (Exception e) { //if its not a double
            paperError.setVisible(true); //display error message
            paperError.setText("* Must be a double"); //let user know that value must be a double
            allDataReceived = false; //if all data is not received do not show confirm message
        }
        
        // Accept salesDistrict entry
        //Make sure that entry exists
        String district;
        if (northButton.isSelected()) { //if north radio button is selected
            district = "North"; //set district to north
            s.setDistrict(district); //push to sales rep object
            districtError.setVisible(false); //hide error message
            //districtError.setVisible(false); //hide error message
        } else if (southButton.isSelected()) { //if south radio button is selected
            district = "South"; //set district to south
            s.setDistrict(district); //push to sales rep object
            districtError.setVisible(false); //hide error message
        } else if (eastButton.isSelected()) { //if east radio button is selected
            district = "East"; //set district to east
            s.setDistrict(district); //push to sales rep object
            districtError.setVisible(false); //hide error message
        } else if (westButton.isSelected()) { //if west radio button is selected
            district = "West"; //set district to west
            s.setDistrict(district); //push to sales rep object
            districtError.setVisible(false); //hide error message
        } else { //if nothing is selected
            allDataReceived = false; //all data is not received
            districtError.setVisible(true); //let user know field is required
        }
        
        //Accept preferred contact method entry
        //Make sure that entry exists
        String contact;
        if (phoneButton.isSelected()) { //if phone radio button is selected
            contact = "Phone"; //set preferred contact to phone
            s.setContact(contact); //push to sales rep object
            contactError.setVisible(false); //hide error message
        } else if (emailButton.isSelected()) { //if email radio button is selected
            contact = "Email"; //set preferred contact to email
            s.setContact(contact); //push to sales rep object
            contactError.setVisible(false); //hide error message
        } else if (visitButton.isSelected()) { //if visit radio button is selected
            contact = "Visit"; //set preferred contact to visit
            s.setContact(contact); //push to sales rep object
            contactError.setVisible(false); //hide error message
        } else { //if nothing is selected
            allDataReceived = false; //all data is not received
            contactError.setVisible(true); //let user know field is required
        }
        
        //display confirmation only if all fields are valid
        if (allDataReceived) {
            JOptionPane.showMessageDialog(this, s);  //pulls data from the toString method in SalesRep.java
        }
    }//GEN-LAST:event_enterButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        JOptionPane.showConfirmDialog(null, "Are you sure you want to quit?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (true) {
            System.exit(0); //close aplication
        }        
    }//GEN-LAST:event_quitButtonActionPerformed

    private void northButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_northButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_northButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel booksError;
    private javax.swing.JTextField booksInput;
    private javax.swing.ButtonGroup btnGroupContact;
    private javax.swing.ButtonGroup btnGroupDistrict;
    private javax.swing.JLabel contactError;
    private javax.swing.JLabel districtError;
    private javax.swing.JRadioButton eastButton;
    private javax.swing.JRadioButton emailButton;
    private javax.swing.JButton enterButton;
    private javax.swing.JLabel firstNameError;
    private javax.swing.JTextField firstNameInput;
    private javax.swing.JLabel idError;
    private javax.swing.JTextField idInput;
    private javax.swing.JLabel labelBooks;
    private javax.swing.JLabel labelContact;
    private javax.swing.JLabel labelDistrict;
    private javax.swing.JLabel labelFirstName;
    private javax.swing.JLabel labelLastName;
    private javax.swing.JLabel labelPaper;
    private javax.swing.JLabel labelRepId;
    private javax.swing.JLabel labelSales;
    private javax.swing.JLabel labelSalesRep;
    private javax.swing.JLabel labelSupplies;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel lastNameError;
    private javax.swing.JTextField lastNameInput;
    private javax.swing.JRadioButton northButton;
    private javax.swing.JPanel panelContact;
    private javax.swing.JPanel panelDistrict;
    private javax.swing.JPanel panelFormNav;
    private javax.swing.JPanel panelSales;
    private javax.swing.JPanel panelSalesRep;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JLabel paperError;
    private javax.swing.JTextField paperInput;
    private javax.swing.JRadioButton phoneButton;
    private javax.swing.JButton quitButton;
    private javax.swing.JRadioButton southButton;
    private javax.swing.JLabel suppliesError;
    private javax.swing.JTextField suppliesInput;
    private javax.swing.JRadioButton visitButton;
    private javax.swing.JRadioButton westButton;
    // End of variables declaration//GEN-END:variables
}
